### ISSUE TITLE
Use Github Actions to automatically format the code

### ISSUE THREAD

**Issue by adrienbanse** [dionysos-dev/Dionysos.jl#235]
@blegat @JulienCalbert  

https://github.com/domluna/JuliaFormatter.jl
What about using this formatter? We could implement it in Github Actions (see https://github.com/julia-actions/julia-format), and therefore
- either one runs the formatter before all PR (to add in the Developer docs)
- or the Actions will make a PR for it.

**Comment by blegat** [comment]
What we usually do is to add an action that checks if a PR broke formatting. See, e.g., https://github.com/jump-dev/JuMP.jl/blob/master/.github/workflows/format_check.yml
So you still have to add in the dev docs how to format your file because the action won't do it for you it will just error if it's not formatted

**Comment by adrienbanse** [comment]
There's also the option to automatically do the PR if the format isn't respected, so we can also do that

**Comment by blegat** [comment]
Up to you, if you configure VS code well, it's easy to get your files formatted so having a reminder when you forget is enough and having a PR is a bit cumbersome but I'm fine with both

**Comment by adrienbanse** [comment]
Closed by https://github.com/dionysos-dev/Dionysos.jl/pull/239
